name: Test

on:
  pull_request:
    branches: [ master ]

permissions:
  contents: read

jobs:
  test_python:
    name: Python
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

    - uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
      with:
        python-version: '3'

    - name: Install Python Dependencies
      run: pip install -r requirements.txt

    - name: Run Python Tests
      run: python -m unittest discover tests
